server:
  port: 8080
spring:
  config:
    name: schedule
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate.multiTenancy: SCHEMA
      hibernate.tenant_identifier_resolver: com.api.crmapi.config.SchemaTenantIdentifierResolver
      hibernate.multi_tenant_connection_provider: com.api.crmapi.config.MultiTenantConnectionProviderImpl
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: ${DB_SCHEMA}
        jdbc:
          time_zone: UTC
  flyway:
    baseline-on-migrate: true
    locations: resources/db/migration
